### PR TITLE
Challenge: anassajaanan submission

### PR DESCRIPTION
**Pull request by anassajaanan**
Challenge: anassajaanan submission

### CODE REVIEW

**Review by aboullaite — APPROVED** [review]
Interesting strategy :D let's see how it flies

**Comment by anassajaanan** [comment]
@aboullaite Alhamdolillah I have a very good optimal solution, but I am afraid to share it, because anyone will be able to see it Lol, is it possible to make it private

**Comment by aboullaite** [comment]
@anassajaanan unfortunately no.

**Comment by anassajaanan** [comment]
@adnanmerrakchi @aboullaite @chermehdi I really wanted the solutions to be private as I noticed, with all respect, that people at the end went from coming with an optimized solution, to optimizing the optimized solution, since I was the first one to use Gperf, and I don't see diff between k34n4y138's solution and mine. But Alhamdollilah, it was fun challenge.

**Comment by aboullaite** [comment]
@anassajaanan I understand your frustration, but it applies both ways. Do you have any suggestions on how we could have structured this privately ? While keeping it centralised, versioned, and not overwhelming to is to collect individual submissions ? I am all ears

**Comment by anassajaanan** [comment]
Appreciate your understanding and feedback.What I can think of is an automated system where submissions are directly pushed to a private repository maintained by you upon receipt via email or a secure form. But I still see that learning experience will be more valuable if we can get inspired and learn from each other.

**Comment by anassajaanan** [comment]
Hi @aboullaite,

As a young Moroccan developer, I've long admired your work. You're truly an inspiration in our tech community. I'd be incredibly honored if you could spare a moment to look at my recent project:

https://www.linkedin.com/feed/update/urn:li:activity:7231142464307306496/

Any feedback from you would be invaluable for my growth.
Thank you for being a role model to aspiring devs like me.

**Pull request merged**
