### PR TITLE
perf: :zap: squeeze more juice

### PR DESCRIPTION
**Pull request by j-mounim**

### CODE REVIEW

**Review by aboullaite — APPROVED** [review]
Let it burn 🔥

**Comment by j-mounim** [comment]
> Let it burn 🔥

kssiri 7ok lpnowate 🏎️🔥. n7awlo ntal3o JS mazal hhh.

**Comment by aboullaite** [comment]
That indeed worked :D Solid improvement... Results later today :D

**Comment by j-mounim** [comment]
Yata 😍🎉🔥

**Pull request merged**
