### PR TITLE
Challenge: superma-C submission

### PR DESCRIPTION
**Pull request by superma-C**

### CODE REVIEW

**Comment by superma-C** [comment]
Hey, sorry for that 😅 . It might seem big, but it is really the same thing with only few changes to test different parallel approaches. w_Xprocs, means i am using X forks to process the file, similarly for w_Xprocs_Ythreads, where I use X forks with Y pthread in each. For w_Xprocs_1fetch_thread, I run X forks, with each invoking a thread to fetch the file on the side, while the parsing is done on the main one. They all share everything else, all those big arrays are just my custom "HashMap". I just have a good machine to test for all 😛 .

PS: Also there is no cache files this time 😅

**Comment by aboullaite** [comment]
Yeah not much, just a few thousand lines :D I will review/ merge it later today, and let some community members give feedback if needed as well.

Looking forward to this and how fast it will be :D Your target is to beat 11s now 👀

**Comment by superma-C** [comment]
@aboullaite , No pressure please😄 🙏

**Comment by superma-C** [comment]
Found a couple of bottlenecks, I'll get back ASAP

**Pull request closed without merging**
